from typing import Protocol, Iterable
from .entities import Message

class ChatRepository(Protocol):
    def create_session(self) -> int: ...
    def add_message(self, session_id: int, message: Message) -> None: ...
    def list_messages(self, session_id: int, limit: int) -> Iterable[Message]: ...
