from dataclasses import dataclass
from typing import Dict, Any, Optional

from chat.domain.entities import Message
from chat.domain.repositories import ChatRepository
from chat.domain.services import ReportService, ChartService
from chat.infrastructure.llm.sql_chat_service import SqlChatService

@dataclass
class AskDatabase:
    repo: ChatRepository
    llm_service: SqlChatService
    chart_service: Optional[ChartService] = None
    report_service: Optional[ReportService] = None

    def execute(self, session_id: int, user_text: str) -> Dict[str, Any]:
        user_msg = Message(role="user", content=user_text)
        self.repo.add_message(session_id, user_msg)

        history = list(self.repo.list_messages(session_id, limit=12))
        answer = self.llm_service.ask(history, session_id=session_id)

        # Prefer assets generated by the agent tools; if missing, fall back to server-side generation.
        # print(answer.g/et("metadata"))
        existing_meta = answer.get("metadata") or {}

        chart_meta: Dict[str, Any] = {}
        if self.chart_service and not existing_meta.get("chart_url") and existing_meta.get('intent')['wants_chart']:
            chart_meta = self.chart_service.maybe_create_chart(
                session_id=session_id,
                user_title=user_text,
                assistant_answer=answer["answer"],
            )

        report_meta: Dict[str, Any] = {}
        if self.report_service and not existing_meta.get("report_url") and existing_meta.get('intent')['wants_pdf']:
            # Create a PDF report only when the assistant produced a single report table.
            # If a chart was generated by the agent tool, reuse it; otherwise reuse fallback chart.
            chart_path = existing_meta.get("chart_path") or (chart_meta or {}).get("chart_path")
            report_meta = self.report_service.maybe_create_pdf_report(
                session_id=session_id,
                user_title=user_text,
                assistant_answer=answer["answer"],
                chart_path=chart_path,
                llm_trace=(answer.get("metadata") or {}).get("trace"),
            )

        merged_meta = {**(answer.get("metadata") or {}), **(chart_meta or {}), **(report_meta or {})}
        assistant_msg = Message(role="assistant", content=answer["answer"], metadata=merged_meta)
        self.repo.add_message(session_id, assistant_msg)

        return {"answer": assistant_msg.content, "metadata": assistant_msg.metadata or {}}
